routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\BrandController;
use App\Http\Controllers\MeasurementController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\DebtController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\ExpensesController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('loginForm');
});

Route::as('auths.')->group(function () {
    Route::post('login', [ AuthController::class, 'login'])->name('login');
    Route::post('logout', [ AuthController::class, 'logout'])->name('logout');
    Route:: get('/dashboard', [ AuthController::class, 'dashboard'])->name('/dashboard');
});


Route::as('pos.products.')->prefix('products')->group(function() {
    Route::get('/', [ ProductController::class, 'index'])->name('index');
    Route::post('/', [ ProductController::class, 'store'])->name('store');
    // Route::get('/{id}', [ ProductController::class, 'show'])->name('show');
    Route::match(['POST', 'PUT', 'PATCH'],'/{id}', [ ProductController::class, 'update'])->name('update');
    Route::delete('/{id}', [ ProductController::class, 'destroy'])->name('delete');
});

Route::as('pos.orders.')->prefix('orders')->group(function() {
    Route::get('/', [ OrderController::class, 'index'])->name('index');
    Route::post('/', [ OrderController::class, 'store'])->name('store');
    Route::match(['POST', 'PUT', 'PATCH'],'/{id}', [ OrderController::class, 'update'])->name('update');
    Route::delete('/{id}', [ OrderController::class, 'destroy'])->name('delete');
    Route::get('/received', [ OrderController::class, 'received_order'])->name('received');
    Route::put('receive/{id}', [ OrderController::class, 'receive'])->name('receive');
    Route::put('available/{id}', [ OrderController::class, 'make_available'])->name('available');
    Route::put('return/{id}', [ OrderController::class, 'return_order'])->name('return');
    Route::put('price/{id}', [ OrderController::class, 'set_price'])->name('price');
    Route::get('/placed', [ OrderController::class, 'order_placed'])->name('placed');

});

Route::as('pos.categories.')->prefix('categories')->group(function() {
    Route::get('/', [ CategoryController::class, 'index'])->name('index');
    Route::post('/', [ CategoryController::class, 'store'])->name('store');
    Route::get('/{category}', [ CategoryController::class, 'show'])->name('show');
    Route::match(['POST', 'PUT', 'PATCH'],'/{category}', [ CategoryController::class, 'update'])->name('update');
    Route::delete('/{id}', [ CategoryController::class, 'destroy'])->name('delete');
});

Route::as('pos.units.')->prefix('units')->group(function() {
    Route::get('/', [ MeasurementController::class, 'index'])->name('index');
    Route::post('/', [ MeasurementController::class, 'store'])->name('store');
    Route::get('/{id}', [ MeasurementController::class, 'show'])->name('show');
    Route::match(['POST', 'PUT', 'PATCH'],'/{id}', [ MeasurementController::class, 'update'])->name('update');
    Route::delete('/{id}', [ MeasurementController::class, 'destroy'])->name('delete');
});

Route::as('pos.brands.')->prefix('brands')->group(function() {
    Route::get('/', [ BrandController::class, 'index'])->name('index');
    Route::post('/', [ BrandController::class, 'store'])->name('store');
    Route::get('/{id}', [ BrandController::class, 'show'])->name('show');
    Route::match(['POST', 'PUT', 'PATCH'],'/{id}', [ BrandController::class, 'update'])->name('update');
    Route::delete('/{id}', [ BrandController::class, 'destroy'])->name('delete');
});


Route::as('pos.companies.')->prefix('companies')->group(function() {
    Route::get('/', [ CompanyController::class, 'index'])->name('index');
    Route::post('/', [ CompanyController::class, 'store'])->name('store');
    // Route::get('/{id}', [ CompanyController::class, 'show'])->name('show');
    Route::match(['POST', 'PUT', 'PATCH'],'/{id}', [ CompanyController::class, 'update'])->name('update');
    Route::delete('/{id}', [ CompanyController::class, 'destroy'])->name('delete');
});

Route::as('pos.debts.')->prefix('debts')->group(function() {
    Route::get('/', [ DebtController::class, 'index'])->name('index');
    Route::post('/', [ DebtController::class, 'store'])->name('store');
    Route::get('/{id}', [ DebtController::class, 'show'])->name('show');
    Route::match(['POST', 'PUT', 'PATCH'],'/{id}', [ DebtController::class, 'update'])->name('update');
    Route::delete('/{id}', [ DebtController::class, 'destroy'])->name('delete');
});


Route::as('pos.employees.')->prefix('employees')->group(function() {
    Route::get('/', [ EmployeeController::class, 'index'])->name('index');
    Route::post('/', [ EmployeeController::class, 'store'])->name('store');
    // Route::get('/{id}', [ EmployeeController::class, 'show'])->name('show');
    Route::match(['POST', 'PUT', 'PATCH'],'/{id}', [ EmployeeController::class, 'update'])->name('update');
    Route::delete('/{id}', [ EmployeeController::class, 'destroy'])->name('delete');
});


Route::as('pos.measurements.')->prefix('measurements')->group(function() {
    Route::get('/', [ MeasurementController::class, 'index'])->name('index');
    Route::post('/', [ MeasurementController::class, 'store'])->name('store');
    // Route::get('/{id}', [ MeasurementController::class, 'show'])->name('show');
    Route::match(['POST', 'PUT', 'PATCH'],'/{id}', [ MeasurementController::class, 'update'])->name('update');
    Route::delete('/{id}', [ MeasurementController::class, 'destroy'])->name('delete');
});


Route::as('pos.expenses.')->prefix('expenses')->group(function() {
    Route::get('/', [ ExpensesController::class, 'index'])->name('index');
    Route::post('/', [ ExpensesController::class, 'store'])->name('store');
    // Route::get('/{id}', [ ExpensesController::class, 'show'])->name('show');
    Route::match(['POST', 'PUT', 'PATCH'],'/{id}', [ ExpensesController::class, 'update'])->name('update');
    Route::delete('/{id}', [ ExpensesController::class, 'destroy'])->name('delete');
});

Route::as('pos.products.')->prefix('products')->group(function() {
    Route::get('/', [ ProductController::class, 'index'])->name('index');
    Route::post('/', [ ProductController::class, 'store'])->name('store');
    // Route::get('/{id}', [ ProductController::class, 'show'])->name('show');
    Route::match(['POST', 'PUT', 'PATCH'],'/{id}', [ ProductController::class, 'update'])->name('update');
    Route::delete('/{id}', [ ProductController::class, 'destroy'])->name('delete');
});

resources/views/loginForm.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Ne-wave Inventory">
    <meta name="author" content="Next-Wave">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Form|Log in</title>

    <!-- alert -->
    <script src="https://unpkg.com/sweetalert@2.1.2/dist/sweetalert.min.js"></script>
    <link rel="stylesheet" href="assets/font-awesome-4.7.0/css/font-awesome.min.css">

    <!-- Bootstrap + LeadMark main styles -->
    <link rel="stylesheet" href="assets/css/leadmark.css">
    <link rel="stylesheet" href="assets/css/adminlte.min.css">

    <!-- Bootstrap -->
    <link href="../vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="../vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="../vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- Animate.css -->
    <link href="../vendors/animate.css/animate.min.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="../build/css/custom.min.css" rel="stylesheet">
</head>

                   


<body class="login">
<div class="login-background-image">
    <div class="login_wrapper">
        <div class="animate form login_form">
            <section class="login_content">
                <form method="POST" action="{{route('auths.login')}}">
                    @csrf
                   
                    <h1 class="text-center text-info text-cyan pb-2" style="list-style: none; font-family: Exotc350 Bd BT; font-size: 35px;">Login Account</h5>
                    <div class="form-group">
                        <input type="username" name="username" class="form-control tex-white btn-outline-primary rounded-0 font-weight-bold" placeholder="Username"  value="{{ old('username') }}"/>
                        @error('username')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                         @enderror
                    </div>
                    <div class="form-group pt-3">
                        <input type="password" class="form-control text-primary rounded-0 font-weight-bold" name="password" placeholder="Password" value="{{ old('password') }}"/>
                        @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                    </div>

                    <div class="p-4">
                        <button type="submit" class="btn btn-flat btn-block btn-outline-primary font-weight-bolder text-white">Log in</button>
                    </div>

                    <div class="clearfix"></div>

                    <div class="separator text-primary">


                        <div class="clearfix"></div>
                        <br />
                        <div class="text-center">
                            <i class="fa fa-paw"></i>
                        </div>
                        <div>
                            <h1>{{ config('app.name') }}</h1>
                            <p>©2016 All Rights Reserved. Mikesung Nextwave Ltd. Privacy and Terms</p>
                        </div>
                    </div>
                </form>
            </section>
        </div>
    </div>
</div>


<!-- Include Sweet Alert scripts -->
<script src="{{ asset('js/app.js') }}"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    @if($errors->any())
        @foreach($errors->all() as $error)
            Swal.fire({
                title: 'FAILED',
                text: '{{ $error }}',
                icon: 'error',
                timer: 10000
            });
        @endforeach
    @endif
</script>



<script src="https://formspree.io/js/formbutton-v1.min.js" defer></script>
<script>
    window.formbutton =
        window.formbutton ||
        function() {
            (formbutton.q = formbutton.q || []).push(arguments);
        };
    formbutton("create", {
        action:"https://formspree.io/f/xeqwgkvr",
        title: "Contact Us",
        fields: [
            {
                type: "text",
                label: "Name:",
                name: "name",
            },
            {
                type: "email",
                label: "Email:",
                name: "email",
            },
            {
                type: "text",
                label: "Address:",
                name: "address1",
            },
            {
                type: "text",
                label: "&nbsp;",
                name: "address2",
            },
            {
                type: "textarea",
                label: "Message:",
                name: "message",
            },
            {
                type: "checkbox",
                label: "Please send me your monthly newsletter",
                name: "_optin",
            },
            { type: "submit", value: "Send" }
        ],
        styles: {
            fontFamily: "Montserrat",
            modal: {
                border: "1px solid #6D6875",
                boxShadow: "6px 6px 0 #6D6875",
                borderRadius: "0",
            },
            title: {
                padding: "24px 24px 0px 24px",
                background: "rgba(0,0,0,0)",
                color: "#2e2a37",
                fontFamily: "Marcellus SC",
                fontSize: "2em",
            },
            body: {
                padding: "16px 24px 24px",
            },
            field: {
                display: "flex",
            },
            submitField: {
                justifyContent: "flex-end",
            },
            label: {
                width: "40%",
            },
            checkboxLabel: {
                width: "auto",
            },
            input: {
                borderRight: "1px solid rgba(0,0,0,0.1)",
                borderBottom: "1px solid rgba(0,0,0,0.1)",
                borderRadius: "0px"
            },
            button: {
                background: "text-primary",
                fill: "skyblue",
                border: "1px solid #6D6875",
                boxShadow: "3px 3px 0px #6D6875"
            },
            closeButton: {
                textShadow: "0 0 0 #2e2a37",
            }
        },
        initiallyVisible: false
    });
</script>

<!-- Back to Top -->
<!--  <a href="#" class="btn btn-primary btn-square back-to-top"><i class="fa fa-arrow-up"></i></a> -->


<!-- core  -->
<script src="assets/vendors/jquery/jquery-3.4.1.js"></script>
<script src="assets/vendors/bootstrap/bootstrap.bundle.js"></script>

<!-- bootstrap 3 affix -->
<script src="assets/vendors/bootstrap/bootstrap.affix.js"></script>

<!-- Isotope -->
<script src="assets/vendors/isotope/isotope.pkgd.js"></script>

<!-- LeadMark js -->
<script src="assets/js/leadmark.js"></script>
<script src="assets/js/adminlte.min.js"></script>

</body>
</html>